api_version = "2024-10"

[[extensions]]
name = "t:name"
handle = "volume-discount"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.product-discount.run"
  input_query = "src/run.graphql"
  export = "run"

   [extensions.input.variables]
  namespace = "custom-tier-discount"
  key = "discount-values"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
